/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DcrsRouteImport } from './routes/dcrs'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RecoveriesRouteImport } from './routes/recoveries'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiHealthRouteImport } from './routes/api.health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DcrsRoute = DcrsRouteImport.update({
  id: '/dcrs',
  path: '/dcrs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveriesRoute = RecoveriesRouteImport.update({
  id: '/recoveries',
  path: '/recoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dcrs': typeof DcrsRoute
  '/forecasts': typeof ForecastsRoute
  '/operations': typeof OperationsRoute
  '/parts': typeof PartsRoute
  '/programs': typeof ProgramsRoute
  '/recoveries': typeof RecoveriesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dcrs': typeof DcrsRoute
  '/forecasts': typeof ForecastsRoute
  '/operations': typeof OperationsRoute
  '/parts': typeof PartsRoute
  '/programs': typeof ProgramsRoute
  '/recoveries': typeof RecoveriesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dcrs': typeof DcrsRoute
  '/forecasts': typeof ForecastsRoute
  '/operations': typeof OperationsRoute
  '/parts': typeof PartsRoute
  '/programs': typeof ProgramsRoute
  '/recoveries': typeof RecoveriesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dcrs'
    | '/forecasts'
    | '/operations'
    | '/parts'
    | '/programs'
    | '/recoveries'
    | '/reports'
    | '/settings'
    | '/api/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dcrs'
    | '/forecasts'
    | '/operations'
    | '/parts'
    | '/programs'
    | '/recoveries'
    | '/reports'
    | '/settings'
    | '/api/health'
  id:
    | '__root__'
    | '/'
    | '/dcrs'
    | '/forecasts'
    | '/operations'
    | '/parts'
    | '/programs'
    | '/recoveries'
    | '/reports'
    | '/settings'
    | '/api/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DcrsRoute: typeof DcrsRoute
  ForecastsRoute: typeof ForecastsRoute
  OperationsRoute: typeof OperationsRoute
  PartsRoute: typeof PartsRoute
  ProgramsRoute: typeof ProgramsRoute
  RecoveriesRoute: typeof RecoveriesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dcrs': {
      id: '/dcrs'
      path: '/dcrs'
      fullPath: '/dcrs'
      preLoaderRoute: typeof DcrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recoveries': {
      id: '/recoveries'
      path: '/recoveries'
      fullPath: '/recoveries'
      preLoaderRoute: typeof RecoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DcrsRoute: DcrsRoute,
  ForecastsRoute: ForecastsRoute,
  OperationsRoute: OperationsRoute,
  PartsRoute: PartsRoute,
  ProgramsRoute: ProgramsRoute,
  RecoveriesRoute: RecoveriesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
