/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as DcrsRouteImport } from './routes/dcrs'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RecoveriesRouteImport } from './routes/recoveries'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiAuthAcceptInvitationRouteImport } from './routes/api.auth.accept-invitation'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthOrganizationRouteImport } from './routes/api.auth.organization'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiOrganizationIndexRouteImport } from './routes/api.organization.index'
import { Route as ApiOrganizationInvitationsRouteImport } from './routes/api.organization.invitations'
import { Route as ApiOrganizationMembershipsRouteImport } from './routes/api.organization.memberships'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DcrsRoute = DcrsRouteImport.update({
  id: '/dcrs',
  path: '/dcrs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveriesRoute = RecoveriesRouteImport.update({
  id: '/recoveries',
  path: '/recoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAcceptInvitationRoute = ApiAuthAcceptInvitationRouteImport.update({
  id: '/api/auth/accept-invitation',
  path: '/api/auth/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOrganizationRoute = ApiAuthOrganizationRouteImport.update({
  id: '/api/auth/organization',
  path: '/api/auth/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationIndexRoute = ApiOrganizationIndexRouteImport.update({
  id: '/api/organization/',
  path: '/api/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationInvitationsRoute =
  ApiOrganizationInvitationsRouteImport.update({
    id: '/api/organization/invitations',
    path: '/api/organization/invitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationMembershipsRoute =
  ApiOrganizationMembershipsRouteImport.update({
    id: '/api/organization/memberships',
    path: '/api/organization/memberships',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/contracts': typeof ContractsRoute
  '/dcrs': typeof DcrsRoute
  '/forecasts': typeof ForecastsRoute
  '/operations': typeof OperationsRoute
  '/organization': typeof OrganizationRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recoveries': typeof RecoveriesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/accept-invitation': typeof ApiAuthAcceptInvitationRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/organization': typeof ApiAuthOrganizationRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/organization/invitations': typeof ApiOrganizationInvitationsRoute
  '/api/organization/memberships': typeof ApiOrganizationMembershipsRoute
  '/api/organization/': typeof ApiOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/contracts': typeof ContractsRoute
  '/dcrs': typeof DcrsRoute
  '/forecasts': typeof ForecastsRoute
  '/operations': typeof OperationsRoute
  '/organization': typeof OrganizationRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recoveries': typeof RecoveriesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/accept-invitation': typeof ApiAuthAcceptInvitationRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/organization': typeof ApiAuthOrganizationRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/organization/invitations': typeof ApiOrganizationInvitationsRoute
  '/api/organization/memberships': typeof ApiOrganizationMembershipsRoute
  '/api/organization': typeof ApiOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/contracts': typeof ContractsRoute
  '/dcrs': typeof DcrsRoute
  '/forecasts': typeof ForecastsRoute
  '/operations': typeof OperationsRoute
  '/organization': typeof OrganizationRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/recoveries': typeof RecoveriesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/accept-invitation': typeof ApiAuthAcceptInvitationRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/organization': typeof ApiAuthOrganizationRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/organization/invitations': typeof ApiOrganizationInvitationsRoute
  '/api/organization/memberships': typeof ApiOrganizationMembershipsRoute
  '/api/organization/': typeof ApiOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/contracts'
    | '/dcrs'
    | '/forecasts'
    | '/operations'
    | '/organization'
    | '/parts'
    | '/profile'
    | '/programs'
    | '/recoveries'
    | '/reports'
    | '/settings'
    | '/api/health'
    | '/api/auth/accept-invitation'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/organization'
    | '/api/auth/session'
    | '/api/organization/invitations'
    | '/api/organization/memberships'
    | '/api/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/contracts'
    | '/dcrs'
    | '/forecasts'
    | '/operations'
    | '/organization'
    | '/parts'
    | '/profile'
    | '/programs'
    | '/recoveries'
    | '/reports'
    | '/settings'
    | '/api/health'
    | '/api/auth/accept-invitation'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/organization'
    | '/api/auth/session'
    | '/api/organization/invitations'
    | '/api/organization/memberships'
    | '/api/organization'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/contracts'
    | '/dcrs'
    | '/forecasts'
    | '/operations'
    | '/organization'
    | '/parts'
    | '/profile'
    | '/programs'
    | '/recoveries'
    | '/reports'
    | '/settings'
    | '/api/health'
    | '/api/auth/accept-invitation'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/organization'
    | '/api/auth/session'
    | '/api/organization/invitations'
    | '/api/organization/memberships'
    | '/api/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ContractsRoute: typeof ContractsRoute
  DcrsRoute: typeof DcrsRoute
  ForecastsRoute: typeof ForecastsRoute
  OperationsRoute: typeof OperationsRoute
  OrganizationRoute: typeof OrganizationRoute
  PartsRoute: typeof PartsRoute
  ProfileRoute: typeof ProfileRoute
  ProgramsRoute: typeof ProgramsRoute
  RecoveriesRoute: typeof RecoveriesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthAcceptInvitationRoute: typeof ApiAuthAcceptInvitationRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthOrganizationRoute: typeof ApiAuthOrganizationRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiOrganizationInvitationsRoute: typeof ApiOrganizationInvitationsRoute
  ApiOrganizationMembershipsRoute: typeof ApiOrganizationMembershipsRoute
  ApiOrganizationIndexRoute: typeof ApiOrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dcrs': {
      id: '/dcrs'
      path: '/dcrs'
      fullPath: '/dcrs'
      preLoaderRoute: typeof DcrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recoveries': {
      id: '/recoveries'
      path: '/recoveries'
      fullPath: '/recoveries'
      preLoaderRoute: typeof RecoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/accept-invitation': {
      id: '/api/auth/accept-invitation'
      path: '/api/auth/accept-invitation'
      fullPath: '/api/auth/accept-invitation'
      preLoaderRoute: typeof ApiAuthAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/organization': {
      id: '/api/auth/organization'
      path: '/api/auth/organization'
      fullPath: '/api/auth/organization'
      preLoaderRoute: typeof ApiAuthOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/': {
      id: '/api/organization/'
      path: '/api/organization'
      fullPath: '/api/organization/'
      preLoaderRoute: typeof ApiOrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/invitations': {
      id: '/api/organization/invitations'
      path: '/api/organization/invitations'
      fullPath: '/api/organization/invitations'
      preLoaderRoute: typeof ApiOrganizationInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/memberships': {
      id: '/api/organization/memberships'
      path: '/api/organization/memberships'
      fullPath: '/api/organization/memberships'
      preLoaderRoute: typeof ApiOrganizationMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  ContractsRoute: ContractsRoute,
  DcrsRoute: DcrsRoute,
  ForecastsRoute: ForecastsRoute,
  OperationsRoute: OperationsRoute,
  OrganizationRoute: OrganizationRoute,
  PartsRoute: PartsRoute,
  ProfileRoute: ProfileRoute,
  ProgramsRoute: ProgramsRoute,
  RecoveriesRoute: RecoveriesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthAcceptInvitationRoute: ApiAuthAcceptInvitationRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthOrganizationRoute: ApiAuthOrganizationRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiOrganizationInvitationsRoute: ApiOrganizationInvitationsRoute,
  ApiOrganizationMembershipsRoute: ApiOrganizationMembershipsRoute,
  ApiOrganizationIndexRoute: ApiOrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
